
spring:
  web-flux:
    base-path: /v1/shipment
  application:
    name: label-generation-service
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    mode: TEXT
    content-type: text/html

# THYMELEAF (ThymeleafAutoConfiguration)
#  spring.thymeleaf.prefix=classpath:/templates/
#  spring.thymeleaf.suffix=.html
#  spring.thymeleaf.mode=HTML5
#  spring.thymeleaf.encoding=UTF-8
#  spring.thymeleaf.content-type=text/html # ;charset=<encoding> is added
#  spring.thymeleaf.cache=true # set to false for hot refresh
management:
  server:
    servlet:
      context-path: /
  endpoints:
    web:
      exposure:
        include: info, health, metrics, loggers, trace, mappings, configprops, env
  info:
    git:
      mode: full
  metrics:
    enable:
      all: true

logging:
  level:
    root: INFO

ai:
  sahyog:
    swagger:
      title: Welink.ai - OpenAPI Spec
      description: This Welink Open Commerce Network API specifications on the OpenAPI 3.0.
      version: 1.0.0
      contact-email: tech@sahyog.ai
      termsOfService: https://welink.ai/terms/
    base64ExclusionListForZpl:
    templateMetadata:
      TEST:
        - "CarrierTrackingNumber2DBarcode"
        - "CarrierTrackingNumberBarcode128"